filecoin-project/slingshot

- participants/yolo.md
Yolo is a decentralized images dataset to develop ML and AI models based on Filecoin and IPFS. We are planning to store [Open Images Dataset](https://storage.googleapis.com/openimages/web/index.html) to Filecoin and IPFS network by Powergate, and continue to enrich and improve it to be a decentralized dataset for computer vision research.
> Yolo project join Slingshot

- participants/Decentralized Docker Hub.md
add Decentralized Docker Hub.md
> add Decentralized Docker Hub.md

- participants/ipfsNewBund.md
The **ipfsNB** is a video site build on IPFS and Filecoin network.
> add the PR for ipfsNewBund project

- participants/slingshot-scavenger-hunt.md
A collaborative information collection game that uses Filecoin!
> Slingshot Scavenger Hunt

- participants/Decentral MyISOs.md
MyISOs is free software for quick and easy installation of the operating system (OS) GNU/Linux on your devices.
> Decentral MyISOs

- participants/Decentral MyBooks.md
Mybooks is an easy to use application to read or listen to the classics books and stories.
> Decentral MyBooks

- participants/ipfsNewBund.md
Thanks for your suggestions. I've updated the PR to only support browse and download at the initial stage. Also mentioned about the free/premium contents and the copyrights in ## (8). And the line breaks were added.
> Update ipfsNewBund.md as suggested.

- participants/vbank.md
The Vbank Platform, using ipfs storage, to build a time bank for medical care workers, medical social workers and medical volunteers, improve the performance indicator system of medical services, and form a new mode of integration of medical health and public welfare by matching service resources with big data of patients' needs.
- **We Storage multiple type of data to prove the authenticity of an hour of volunteering**
- [image] pictures of Service process.
- [json] iBeacon positioning report data from iot.
- [video] Monitor snapshot & records.
- [audio] Wearable smart terminal records.
- **We provide a data browser to check for authenticity using hashes**
- [person] Who did
- [process] what did
- [review] Who reviewed
- **We provide a Trading center using time currency**
- one hour, …
> docs: vbank.md new project request

- participants/matin-cloud-pan.md
This application provides individuals with secure data storage services based on ipfs and lotus, and will develop real-time broadcast functions in the future.
>  upload readme

- participants/dragonfly.md
Dragonfly by Diancun Tech
Dragonfly is a distributed docker registry.
> Dragonfly by Diancun Tech

- participants/YuncunHorizon.md
https://github.com/AlexY0905/slingshot-app   The design concept of our app is to design a suitable platform for users to search data, hoping to get official recognition.
> YuncunHorizon

- participants/IPFSPAN.md
IPFSPAN Projects join slingshot
> IPFSPAN Projects join slingshot

- participants/TicMusi.md
A project proposed for space race 2
> Project name: TicMusi

- participants/chain-snapshot.md
Chain Snapshot is a repository where backup blockchain data from cryptocurrencies. Include but not limited to Filecoin, Bitcoin, Ethereum, Dogecoin, ZCash, Litecoin, Dash, Bitcoin Cash, Ethereum Classic, etc.
> Chian Snapshot project request

- participants/OriginSound.md
The copyright blockchain system developed by the Original Sound adopts the form of alliance chain, which can efficiently handle the copyright business of various digital works categories (text, pictures, video, etc.). 
It has more efficient business data throughput ability to realize real-time business processing. It becomes possible to have a large number of Internet creation righted timely with low cost, 
to achieve rapid transaction circulation.Now we are ready to migrate our existing user data to IPFS.
> OriginSound

- participants/webcam-monitor.md
It aims to store the surveillance data collected by surveillance cameras in ipfs and filecoin via the network.
Ensure the security of monitoring data and facilitate later playback of data. Make up for the shortcomings of traditional monitoring data that is only stored for one month, and high-definition data takes up a lot of space.
> webcam-monitor

- participants/Decentral Myvlog.md
Myvlog is a free app that automatically jump-cut edits your videos without the annoying editing.
> Decentral Myvlog

- participants/pServer.md
pServer is both a demander of ipfs/filecoin and a storage provider of ipfs/filecoin.
> pServer by ARS

- participants/yolo.md
@yuwenhui  - I've restored this file.  Can you verify it's the correct version?  I'm not sure of the root cause but wanted to restore your entry ASAP.
> re-added yolo.md

- participants/Hipool cloud disk.md
> verification code is:

- participants/IPFS-Found.md
Based on Filecoin network, we develop an application platform for storage and retrieval to help users store various types of files, including text, picture, audio, video, etc. [IPFS Found](https://filecoin.in) supports storage of multiple data sizes. We aim to build more decentralized, stable and robust data storage platform.
> IPFS Found

- datasets.md
ISO datasets https://www.linuxlookup.com/linux_iso
> add linux iso to datasets

- datasets.md
Adding first two curated sets we will be using.
> Update Curated Data Sets

- participants/vof.md
add the introduction of VOF(Video Over Filecoin)
> add the introduction of VOF

- participants/Filvr.md
please check it out,thank you!
> add Filvr-PR

- participants/SwiftCloudBackup.md
Add the basic introduction of Swift Cloud Backup. We believe that Filecoin will be very important cloud storage infrastructure in the future!
> Add the basic introduction of Swift Cloud Backup.

- participants/biodivsync.md
> Add BioDivSync to datasets

- participants/Everyone's ipfslife memories.md
Store Everyone's ipfslife memories, Never lose.
> Everyone's ipfslife memories.md

- participants/FGDC.md
The Filecoin Genomics Data Center (FGDC) is an open and free data center for storing genes, using blockchain to provide a data center that will never be lost for all mankind.
> The Filecoin Genomics Data Center (FGDC)

- participants/Smartcity Sensor-based network and data analysis system.md
> add PR for SR2 to register

- participants/We Rave You.md
> Add We Rave You Project

- participants/Music-Wiki.md
> add project Music-Wiki

- participants/HarborCloud.md
> Create Harbor Cloud

- participants/Novel-Wiki.md
add project Novel-Wiki (Submission ID: 674639480)
> add project Novel-Wiki

- participants/op-mirrors.md
> add op-mirrors project

- participants/FileZoo.md
FileZoo is an interesting storage application for the slingshot competition.
@pooja please help me review it
> Introduction of FileZoo

- participants/BlueSkyVideo.md
Added Blue Sky Video Project, please have a review.
> Add Blue Sky Video Project

- miners.json
I am the operator of t014365, have configured it to accept deals, and would like to list my miner.
> Add my miner to Oceania miners.json

- datasets.md
Wants to add Project Gutenberg to filecoin currated dataset. 
Project gutenberg content is public. How we should proceed to upload that data.
We're going to use it for dCompute slingshot project. I'm ready to upload it to filecoin.
Thank you,
Julien
> Add Project Gutenberg to currated datasets

- participants/Let's Talk
> Create Let's Talk

- participants/FairWebLivetreeSlingshotEntry.md
Before submitting a PR containing your team's project information:
- Make sure you rename this file to contain your project's name
- Respond to add your response in each section below
Submission: hacked-vegan-spider
Project Name: Livetree 
Team Slack Handles: Multiple (Ashley Turing / Andrew / Greg)
Since 2018 Livetree has built up a range of video solutions that can be operated via our own cloud. We are seeking to decentralise the solution, through the migration of our storage of video files and related meta-data using FileCoin.io. At a later stage we will be looking to replace our CDN networks with Filecoin and rollout our own media-object video protocol which encompasses DRM and transcoding services.  
fairweb.livetree.com
Over-the-top streaming platform
We are using files from our …
> Slingshot.filecoin.io Application see participants\FairWebLivetreeSlingshotEntry.md

- participants/filshare.md
Project Name:Filshare
Slack: Seven
Submission ID: 677173782
thank for reviewing this pr
> Filshare dapp

- participants/GaiaCloud.md
> Gaia Cloud

- participants/datashop.md
Datashop Term request to participate Slingshot of filecoin and add  datashop.md file
> Datashop Term request to participate Slingshot of filecoin and add  datashop.md file

- participants/Cadbury.md
Details out the information required for slingshot competition.
> Cadbury Slingshot Proposal

- participants/IPFSmartCloud.md
i want to join Filecoin Storage.
> IPFS SmartCloud 

- participants/BlockcastingCloud.md
Blockcasting Cloud is a decentralized network disk which allows users to store public and private data.
> Blockcasting pr

- participants/FileWarehouse.md
Based on the Filecoin network, we build an AI training dataset storage and cloud computing platform.
I have registered in the [slingshot.filecoin.io](slingshot.filecoin.io), please review my project @pooja @dineshshenoy , my web will be re-designed, we need more time to do that, thank you.
> FileWarehouse

- participants/Healthchain-future.md.txt
- 参加者/Healthchain-future.md.txt
User health data management, help users to authentic  their own health data rights, sharing and trading. The combination of home medical testing equipment and insurance can help users do self-health management and medical claims
> Healthchain-Future（HCF)

- participants/FILKITTENS.md
```
You'll need your verification code for the next step of the process. 
Your verification code is:
penpal-plank-violation
(Submission ID: 681056236)
```
thanks for your reviewing
> FILKITTENS

- participants/FMABrowser.md
> Update project proposal

- participants/Panfil.md
Join SR2 Slingshot  and need review 
请审核
> Join SR2 Slingshot  and need review

- participants/FilPocket.md
Your verification code is:
cage-tusk-raven
(Submission ID: 678911992)
Thank for reviewing the code.
> filpocke dapp

- participants/IPOS Browser.md
> IPOS Browser

- internal/stats_rollup.txt
See comment in file. This is needed for the stats website. Feel free to start editing it as per the instruction / adding participants
> Stats rollup list

- datasets.md
Hi, I would like to add these specific dataset back. They are under CC-license.
> Add specific dataset in AWS and InternetArchive

- datasets.md
Add a few more datasets hosted on Azure.
Discussed in #464
> Add a few more datasets hosted on Azure

- recovery/files/client-list.json
- recovery/files/dataset-list.json
- `client-list.json` contains a list of clients participating in the Slingshot Recovery program and their `client_address`es
- `dataset-list.json` contains a list of dataset slug/name key-value pairs for datasets being restored in the Slingshot Recovery program
> feat: Added `client-list.json` and `dataset-list.json` to Recovery

- .github/ISSUE_TEMPLATE/dataset-extension-request.md
- .github/ISSUE_TEMPLATE/request-or-suggestion-for-slingshot-recovery.md
- .github/ISSUE_TEMPLATE/request-to-rename-project.md
- .github/ISSUE_TEMPLATE/request-to-transfer-project.md
- .github/ISSUE_TEMPLATE/slingshot-v3-dataset-request.md
- .github/ISSUE_TEMPLATE/slingshot-v3-dp-change.md
- .github/ISSUE_TEMPLATE/slingshot-v3-issue.md
Minor updates to the existing Slingshot v3 issue templates. Primarily these are to:
- Standardize naming convention (may change later)
- Add tags and other metadata to the appropriate issues
@dkkapur, the content looks good to me! I didn't change anything with regard to the actual wording.
> feat: v3 issue template updates
